application: form-filler
version: 1
runtime: python
api_version: 1

handlers:
  
- url: /static/
  static_dir: static/
  
- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: .*
  script: www/index.py
  # login: required

# inbound_services:
#  - xmpp_message
