application: formfiller
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: static/css
  
- url: /js
  static_dir: static/js
  
- url: /img
  static_dir: static/img

- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
    
- url: .*
  script: main.py
  # login: required

# inbound_services:
#  - xmpp_message